<?php
/**
 * This file has been automatically generated by yii2-enum, do not change it manually.
 * @date  */

namespace opus\elastic\enum;

/**
 * Enumeration category ElasticFieldType.
 *
 * @package opus\elastic\enum
 */
class ElasticFieldType
{
    const INTEGER = 'integer';
    const STRING = 'keyword';
    const ANALYZED_STRING = 'analyzed_string';
    const ANALYZED_STRING_WITH_RAW = 'analyzed_string_with_raw';
    const OBJECT = 'object';
    const DATE = 'date';
    const NESTED = 'nested';
    const FLOAT = 'float';
    const BOOLEAN = 'boolean';
}
